name: 'Testing config import'
type: profile
description: 'Tests install profiles in the config importer.'
# version: VERSION
# core: 8.x
hidden: true
dependencies:
  - syslog
themes:
  - stark

# Information added by Drupal.org packaging script on 2017-06-07
version: '8.3.3'
core: '8.x'
project: 'drupal'
datestamp: 1496858154
